INSERT INTO departments (name) VALUES
('Seguridad'),
('Contraloría'),
('A y B'),
('Compras'),
('Gerencias'),
('Facturas'),
('Calidad'),
('Almacén'),
('RH'),
('Operadora'),
('Ventas'),
('Recepción'),
('Restaurante'),
('Áreas Públicas'),
('Ama de Llaves'),
('Mantenimiento'),
('CV / Tours'),
('Animación'),
('Bellboy'),
('Spa'),
('Sistemas'),
('Alimentos'),
('Cobranza'),
('Concierge');